package edu.utm.creational;
class Wizard implements Cloneable {
	private String name;
	private String spell;
	private String talent;

	public Wizard(String name, String spell, String talent) {
		this.name = name;
		this.spell = spell;
		this.talent = talent;
	}

	// assure deep copying
	public Wizard clone() {
		Wizard copyWizard = new Wizard(name, spell, talent);
		return copyWizard;
	}

	public String toString() {
		return "Wizard " + name + "\nspell: " + spell + "\ntalent: " + talent
				+ "\n\n";
	}

	// autogenerated code
	public String getSpell() {
		return spell;
	}

	public void setSpell(String spell) {
		this.spell = spell;
	}

	public String getTalent() {
		return talent;
	}

	public void setTalent(String talent) {
		this.talent = talent;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}

public class Prototype {

	public static void main(String[] args) {
		Wizard harry = new Wizard("Harry", "Expecto Patronum", "Possum tongue");
		System.out.println(harry.toString());

		Wizard ron = harry.clone();
		ron.setName("Ron");
		ron.setSpell("Wingardium Leviosa");
		ron.setTalent("Chess player");
		System.out.println(ron.toString());

		Wizard hermione = harry.clone();
		hermione.setName("Hermione");
		hermione.setSpell("Alohomora");
		hermione.setTalent("Cleverness");
		System.out.println(hermione.toString());
	}

}
